- name: add ssh key for simone
  tags: always
  authorized_key:
    user: simone
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC5fi2CbGm8FBD9tSz+DLNN/lX0BGyzvAdg0XC2xNJJSlWZuU1obH7k5UWIiSmgeUxyAWL1hOQaA4cD8THgXQrZcs79GoIX4HdoN/qWAEeyD0YruEgREYG2WK+Sao2s9wSzu1t6eRinH7d2Jf1+0Ja3ZUVkIEIytNR5UQ0Fjq2UiLYPwa5ca/ZhhMEczTSPM3mTjRfKa9xg/7WD51FyaMy0HVFW9RIsUC7aFLbm8pNEe9DEsIua8GK8G4m22hYBibkmkNlXVmPF8bcfx+tcxzeunT7eSwrYgDfVYXN/cXc2B38emuLwIcSqhLFONBMCpazWYq05jJ2Mg01OXEv4E/QVqeWa4TmbAi+mSEpx4MSkvmmFXO4a73xbFpBope7Xc/PJSghLoz4GDDlQRKftJqK697d5cJ2K6WotPBwcyP0BnYvltclLfHGFIxx9b++YNOMm7xzAlAmjVIMiEyGfUOfDQ+DfhD4NrH66Gxx3jwPNpIMjhaPkhqOdjMfeG4r/o3k= user1@3eeebb43d83e"
